CREATE TABLE IF NOT EXISTS public.groups
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    number character varying not null,
    faculty character varying not null,
    year_of_create character varying not null,
    is_archive boolean not null,
    CONSTRAINT groups_pkey PRIMARY KEY (id),
    CONSTRAINT group_number UNIQUE (number,year_of_create)
);
CREATE TABLE IF NOT EXISTS public.students
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying not null,
    date_of_enrollment date not null,
    group_id int not null,
    CONSTRAINT "FK_GROUP" FOREIGN KEY (group_id) REFERENCES groups(id),
    CONSTRAINT students_pkey PRIMARY KEY (id)
);